spring:
  datasource:
    url: jdbc:clickhouse://localhost:8123/default?compress=0
    username: myuser
    password: mypassword
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver

server:
  port: 8081