spring:
  datasource: # MariaDB
    url: jdbc:mariadb://localhost:3306/default
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  redis:
    host: localhost
    port: 6379

clickhouse:
  datasource:
    url: jdbc:clickhouse://localhost:8123/default?compress=0
    username: myuser
    password: mypassword
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver

